"""
Processes synthetic patient data generated by Synthea.
Displays column headers and the first five rows of the dataset.
"""
import pandas as pd

csv_urls = {
    'person': 'https://raw.githubusercontent.com/jhajagos/SyntheaData520/main/person.csv',
    'death': 'https://raw.githubusercontent.com/jhajagos/SyntheaData520/main/death.csv',
    'visit_occurrence': 'https://raw.githubusercontent.com/jhajagos/SyntheaData520/main/visit_occurrence.csv',
    'concept': 'https://raw.githubusercontent.com/jhajagos/SyntheaData520/main/concept.csv',
    'condition_occurrence': 'https://raw.githubusercontent.com/jhajagos/SyntheaData520/main/condition_occurrence.csv',
    'location': 'https://raw.githubusercontent.com/jhajagos/SyntheaData520/main/location.csv'
}

# Iterate through the dictionary
for key, url in csv_urls.items():
    try:
        # Read CSV from URL into a DataFrame
        df = pd.read_csv(url)
        
        # Print the key (name)
        print(f"\n{key.upper()}:")

        # Print the column headings
        print("\nColumn Headings:")
        print(list(df.columns))
        
        # Print the head (first 5 rows) of the DataFrame
        print("\nFirst 5 Rows:")
        print(df.head())

    except Exception as e:
        print(f"Error reading {key}: {str(e)}")
